language: python

python:
  - "2.7"
  - "3.6"

before_install:
- pip install Cython --install-option="--no-cython-compile"

install:
# This works because requirements-dev.txt ends with "-e ." to install COMPAS itself
- pip install --no-cache-dir -r requirements-dev.txt

script:
- invoke test
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
    invoke docs;
  fi

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  repo: compas-dev/main
  name: COMPAS doc bot
  target-branch: master
  local_dir: dist/docs
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = 3.6
