name: docs

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build and deploy docs
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{secrets.GH_PAT}}
    steps:

      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          miniconda-version: "latest"
          activate-environment: compas-dev
          channels: conda-forge
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cython --install-option="--no-cython-compile"
          conda install graphviz

      - name: Install
        run: |
          python -m pip install --no-cache-dir -r requirements-dev.txt
      - name: Generate docs
        if: ${{ success() }}
        run: |
          invoke docs
          # Get branch/tag/latest name from git
          GITHUB_REF_REGEX="tags/v[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}|(pull/[0-9]+)|heads/master"
          if [[ $GITHUB_REF =~ $GITHUB_REF_REGEX ]]; then
              if [[ $BASH_REMATCH = pull* ]]; then
                  echo This is a pull request
                  FOLDER_NAME=pull_${BASH_REMATCH##*/}
              elif [[ $BASH_REMATCH = tags/* ]]; then
                  echo This is a version tag
                  FOLDER_NAME=${BASH_REMATCH##*/v}
              else
                  echo This is a commit to master branch
                  FOLDER_NAME=latest
              fi;
          fi;
          echo "Docs will be deployed to https://compas.dev/compas/$FOLDER_NAME"
          mkdir -p deploy/$BRANCH_OR_TAG && mv -T dist/docs deploy/$FOLDER_NAME/
      - name: Deploy docs
        if: success() && env.GH_PAT != ''
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: deploy
          keep_history: true
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

  docVersions:
    needs: build
    name: update doc versions
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{secrets.GH_PAT}}
    steps:

      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: update doc versions
        run: |
          >doc_versions.txt
          for folder in $(ls -rd */ | tr -d '/')
          do 
              if [[ $folder =~ ^[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}$|^latest$ ]]
              then 
                  echo ${folder}  >> doc_versions.txt
              fi
          done
          echo found available doc versions:
          cat doc_versions.txt

      - name: Deploy docs
        if: success() && env.GH_PAT != ''
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./
          keep_history: false  
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
