name: docs

on:
  push:
    branches:
      - main
      - '*.LTS'
    tags:
      - 'v*'
  pull_request_review:
    types: [submitted]

jobs:
  docs:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'pull_request_review' && github.event.review.state == 'approved')
    runs-on: ubuntu-latest
    steps:
      - uses: compas-dev/compas-actions.docs@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          doc_url: https://compas.dev/compas
