name: ironpython

on:
  push:
    branches:
      - main
      - '*.LTS'
  pull_request:
    branches:
      - main
      - '*.LTS'

jobs:
  build:
    name: windows-ironpython
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: "[RPC tests] Set up CPython 3.9"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "[RPC tests] Install CPython dependencies"
        run: |
          python -m pip install --upgrade pip
      - name: "[RPC tests] Install COMPAS on CPython"
        run: |
          pip install --no-cache-dir .
      - name: Install dependencies
        run: |
          choco install ironpython --version=2.7.8.1
          curl -o ironpython-pytest.tar.gz -LJO https://pypi.debian.net/ironpython-pytest/latest
          ipy -X:Frames -m ensurepip
          ipy -X:Frames -m pip install --no-deps ironpython-pytest.tar.gz
      - uses: NuGet/setup-nuget@v1.0.5
      - name: Install dependencies
        run: |
          choco install ironpython --version=2.7.8.1
      - uses: compas-dev/compas-actions.ghpython_components@v2
        with:
          source: src/compas_ghpython/components
          target: src/compas_ghpython/components
      - name: Test import
        run: |
          ipy -m compas
        env:
          IRONPYTHONPATH: ./src
      - name: Run tests
        run: |
          ipy tests/ipy_test_runner.py
        env:
          IRONPYTHONPATH: ./src
